### ISSUE TITLE
downtime and event...

### ISSUE THREAD

**Issue by runtimevic** [ravener/stopwatch.py#6]
Hello @ravener , @erickang21 :

I would like to have a countdown timer, downtime...
in which the time for the countdown could be configured and when reaching the countdown it would give us an event that it has reached time 0 of the countdown?
- Can it be obtained with this library?
- Or would it be an improvement to this library?
thanks you, Víctor.

**Comment by ravener** [comment]
Hi,

Sorry but a stopwatch is only supposed to count the elapsed time for basic benchmarking purposes and so a countdown is out of the scope of this project, since you also want to know when the timer reaches zero that will be opinionated regarding how events are handled and it'd require an event loop or similar patterns to handle events.

**Comment by runtimevic** [comment]
> Hi,
> 
> Sorry but a stopwatch is only supposed to count the elapsed time for basic benchmarking purposes and so a countdown is out of the scope of this project, since you also want to know when the timer reaches zero that will be opinionated regarding how events are handled and it'd require an event loop or similar patterns to handle events.

Hi @ravener ,

I found this library, do you think it will help me?
https://github.com/Saadmairaj/date-time-event
What I don't know is how to know how much time I have left? in this other library...
